name: ST-CashShop
main: net.starly.cashshop.CashShopMain
author: Starly Team
website: http://starly.kr/discord

description: CashShop Plugin.

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13
permissions:
  starly.cashshop.npc:
    description: npc command
  starly.cashshop.create:
    description: create command
  starly.cashshop.remove:
    description: remove command
  starly.cashshop.edit:
    description: edit command
  starly.cashshop.list:
    description: list command
  starly.cashshop.open:
    description: open command
  starly.cashshop.info:
    description: info command
  starly.cashshop.add:
    description: add command
  starly.cashshop.sub:
    description: sub command
  starly.cashshop.set:
    description: set command
  starly.cashshop.reset:
    description: reset command
  starly.cashshop.reload:
    description: reload command

commands:
  cash:
    aliases: [캐시]
  cashshop:
    aliases: [캐시상점]
